# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    groups:
      prod-update:
        dependency-type: "production"
        update-types:
          - "patch"
          - "minor"
      dev-update:
        dependency-type: "development"
        update-types:
          - "patch"
          - "minor"
          - "major"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      docs-update:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/admin-frontend/"
    schedule:
      interval: "monthly"
    groups:
      prod-update:
        dependency-type: "production"
        update-types:
          - "patch"
          - "minor"
      dev-update:
        dependency-type: "development"
        update-types:
          - "patch"
          - "minor"
          - "major"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    groups:
      actions-update:
        patterns:
          - "*"
