name: test-build

on:
  push:
    branches:
      - main
      - next
    paths:
      - admin-frontend/**
      - docker/**
      - nonebot_bison/**
      - tests/**
      - pyproject.toml
      - poetry.lock
      - .github/**
  pull_request:
    paths:
      - admin-frontend/**
      - docker/**
      - nonebot_bison/**
      - tests/**
      - pyproject.toml
      - poetry.lock
      - .github/**
    types:
      - opened
      - synchronize
      - reopened
      # 以上为默认情况
      - labeled
      - unlabeled

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Frontend
        uses: ./.github/actions/build-frontend

      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: ./admin-frontend/build/
  test:
    name: Smoke-test Coverage
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'all-test') }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    env:
      OS: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python environment
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install prerequisites
        run: poetry install

      - name: Run Pytest
        run: poetry run pytest --cov-report xml --cov=./nonebot_bison -k 'not compare and not render' -n auto

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          flags: smoke-test
          env_vars: OS,PYTHON_VERSION

  test-all:
    name: All-test Coverage
    if: ${{ contains(github.event.pull_request.labels.*.name, 'all-test') }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    env:
      OS: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python environment
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install prerequisites
        run: poetry install

      - name: Run Pytest
        run: poetry run pytest --cov-report xml --cov=./nonebot_bison -k 'not compare' -n auto

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          flags: all-test
          env_vars: OS,PYTHON_VERSION
