name: Release

on:
  push:
    tags:
      - v*

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Frontend
        uses: ./.github/actions/build-frontend

      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: ./admin-frontend/build/
  publish-pypi-github:
    runs-on: ubuntu-latest
    needs: build-frontend

    steps:
      - uses: actions/checkout@v3

      - name: Download frontend files
        uses: actions/download-artifact@v2
        with:
          name: frontend
          path: ./nonebot_bison/admin_page/dist

      - name: Setup Python environment
        uses: ./.github/actions/setup-python

      - run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Publish PyPI and Github
        run: |
          poetry publish --build -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }} || echo "Already pushed to pypi"
          gh release upload --clobber ${{ env.TAG_NAME }} dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}